### ISSUE TITLE
Adaptive font color for badges

### ISSUE THREAD

**Issue by Serraniel** [Serraniel/AniwatchPlus#109]
Badges on aniwatch mostly have a white font-color. This results in a bad contrast on some of them, e. g. the organge badge:
![image](https://user-images.githubusercontent.com/8461282/98162978-691ecb00-1ee2-11eb-8bbb-41c927b6af37.png)
(https://aniwatch.me/top?t=0&p=1)

A darker color may be a better solution (quick test with black for demonstration):
![image](https://user-images.githubusercontent.com/8461282/98163043-818ee580-1ee2-11eb-9037-36d7a25dae12.png)

**Comment by Serraniel** [comment]
iMostLiked suggested to test following colors:
`#232323`
![image](https://user-images.githubusercontent.com/8461282/98163124-a7b48580-1ee2-11eb-863e-d67d94c9c469.png)

or
`#282a39`
![image](https://user-images.githubusercontent.com/8461282/98163164-b4d17480-1ee2-11eb-8097-f5b1a2ae512e.png)

**Comment by kaffem** [comment]
I personally like `#232323` more than `#282a39`

**Comment by Serraniel** [comment]
As both of those colors also contain a bit of blue, I still would also try several black or grays for this.

**Comment by Serraniel** [comment]
So, I made a decission on font color: `#282a39` it is. Reason: that color is used by aniwatch themselves as font color for other elements with light background:
![image](https://user-images.githubusercontent.com/8461282/99154267-c834ca80-26ae-11eb-85c6-14c3787fed70.png)

**Comment by Serraniel** [comment]
This issue has been resolved with v1.0 release.
