### ISSUE TITLE
Anilyr: Autoplay/pause on focus change

### ISSUE THREAD

**Issue by kaffem** [Serraniel/AniwatchPlus#173]
Pause the stream when the tab focus is changed, someone forgot to pause it before looking at another tab so the extension autopauses the stream.
The same for autoplay to continue watching the stream.

**Comment by Serraniel** [comment]
> No description provided.

Pain.... 😅

**Comment by kaffem** [comment]
> 
> 
> > No description provided.
> 
> Pain.... 😅

Updated it, something went wrong there with copy paste :D

**Comment by Serraniel** [comment]
Included in release 1.1.0.0.
