### ISSUE TITLE
Watch2Gether: Character count for check only works for host

### ISSUE THREAD

**Issue by Serraniel** [Serraniel/AniwatchPlus#184]
If people join a watch2gether via a link, the character counter for chat messages does not work because of the loading screen.

**Comment by kaffem** [comment]
Executing manipulateChatInput() both afterLoad and afterLocationChange is a potential workaround.

**Comment by Serraniel** [comment]
This is included in the PR which resolves #144 .

**Comment by Serraniel** [comment]
Included in release 1.1.0.0.
