### ISSUE TITLE
Better display of language icons

### ISSUE THREAD

**Issue by Serraniel** [Serraniel/AniwatchPlus#3]
Refined tasks:
- [x] Episode List (Box view)
- [x] Episode List (List view)
- [x] Episode List (Compact view)
- [ ] Player
---

Something else: Dub and sub icons are displayed close together without any relation to each other in the episode list. In the selection below an episode it is a bit random. in that example we have (scheme: *dub (sub)*):
```
jap (en)
en
jap (de)
de
```
![image](https://user-images.githubusercontent.com/8461282/80288077-b94bf200-8735-11ea-8830-4812d4d6428b.png)

I see what you did there: ordering by "seconday" (not jap) language  with dub > sub.
Another idea for an rearrangement would be to put subs for the same dub below each other.
In episode list and episode lang selection, both would profit from that more matrix style display mode. the correlation from dub and sub is shown better and it offers more possibilites to combine dubs and subs (which may be interesting in the future if more languages will come).
![image](https://user-images.githubusercontent.com/8461282/80288101-f57f5280-8735-11ea-8294-f8053ad817cc.png)

(Those images are paint edits so please don´t blame me xd)

**Comment by Serraniel** [comment]
Little addition to this: If there only is sub available, the audio language currently is completly missing on Aniwatch:
![image](https://user-images.githubusercontent.com/8461282/93715614-a4e81600-fb6a-11ea-9c04-4d124da2db85.png)

For a better consistency the Jap audio should be displayed, too.

**Comment by Serraniel** [comment]
@kaffem Do you think this kind of presentation is good with the thin vertical separators? It´s the same type of border we use for the horizontal separators in the list:
![image](https://user-images.githubusercontent.com/8461282/93715662-ec6ea200-fb6a-11ea-8844-90049e5792d1.png)
![image](https://user-images.githubusercontent.com/8461282/93715665-f1cbec80-fb6a-11ea-903b-49b357596190.png)

**Comment by kaffem** [comment]
> Do you think this kind of presentation is good with the thin vertical separators? It´s the same type of border we use for the horizontal separators in the list:

Yeah this looks good.

**Comment by Serraniel** [comment]
Boxed mode also is working now:
![image](https://user-images.githubusercontent.com/8461282/94363066-fee36100-00bf-11eb-999f-93f60654d3e5.png)

Additionally did major performance improvments to the algorithm while adding support for it 👌 .

**Comment by Serraniel** [comment]
Issue #58 has been created as successor for the realignment of the language selection below the player as it is a differnt at all and would blow up the pull request with additional code for a different feature.

**Comment by Serraniel** [comment]
Added with https://github.com/Serraniel/AniwatchPlus/releases/tag/0.2.0.0-beta.0
