### ISSUE TITLE
Quick search hot key triggers when text input is focused

### ISSUE THREAD

**Issue by Serraniel** [Serraniel/AniwatchPlus#54]
When a text input element is focused and the user presses `Shift` + `F` with the intention to type a captial *F* the quick search is focused instead.

**Comment by Serraniel** [comment]
Possible soloution would be to either prevent the event when some type of text input is focused or to change the hotkey. I don´t know yet what the best option would be. Overwriting `Ctrl` + `F` is not an option for me personally, don´t know about maybe `Alt` + `F` or maybe `Ctrl` + `Shift` + `F`?

**Comment by kaffem** [comment]
I personally would go for `Ctrl` + `Shift` + `F`.

**Comment by Serraniel** [comment]
I´ll do this then.

**Comment by Serraniel** [comment]
Maybe not as easy decission as it sounds like.
1) In Chrome, the `event.key` becomes some Unicode char (``) while in Firefox it still is an `F`.
2) The other big problem: it really is hard to trigger the event itself in firefox when pressing `ctrl`. Seems like the browser prevents this while listening to its own hotkeys.

![image](https://user-images.githubusercontent.com/8461282/94721249-e42a1a00-0355-11eb-8002-25ef20625976.png)

**Comment by Serraniel** [comment]
So, I decided to just add a check if the `document.activeElement` is some kind of input ot contentEditable and prevent the hotkey then as a quick fix. 
The behaviour might be improved in future if we found a better solution.

**Comment by Serraniel** [comment]
Fixed with https://github.com/Serraniel/AniwatchPlus/releases/tag/0.2.0.0-beta.0
